blog/urls.py
from django.urls import path
from django.shortcuts import render
from . import views

app_name = 'blog'
urlpatterns = [
    # path('', views.index_view, name='index'),
    path('post-add/', views.post_new, name='add_post'),
    # path('post-detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post-detail/<int:pk>/', views.post_detail, name='post_detail'),
    path('', views.PostsListView.as_view(), name='posts_all'),
    path('user-posts/', views.LoginUserPostsAllView.as_view(), name='user_posts'),
    path('post/<int:pk>/comments', views.CommentAddView.as_view(), name='comment_add'),
    path('post-update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('contact-us/', views.contact_us_view, name='contact_us'),
    path('user_post-detail/<int:pk>/', views.UserPostDetailView.as_view(), name='user_post_detail'),
    path('post-delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user_management.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

user_management/urls.py
from django.urls import include, path
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from . import views


app_name = 'user_management'
urlpatterns = [
    path('registration/', views.RegistrationView.as_view(), name='registration'),

    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("user-detail/", views.UserDetailView.as_view(), name="user_detail"),
    path("user-update/", views.UserUpdateView.as_view(), name="user_update"),
    path("user-detail-pub/<int:pk>/", views.UserProfilePublicDetailView.as_view(), name="user_detail_pub")
]

blog/models.py
from django.db import models
from django.utils import timezone
from django_lifecycle import LifecycleModel, hook, AFTER_UPDATE
from django.urls import reverse
from django.conf import settings
from .tasks import send_mail as celery_send_mail


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Comments(LifecycleModel):
    username = models.CharField(max_length=200)
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    published = models.BooleanField(default=False)

    @hook(AFTER_UPDATE, when='published', was=False, is_now=True)
    def owner_inform(self):
        post_id = self.post.id
        mail_to = self.post.user.email
        get_url = reverse('blog:post_detail', args=[post_id])
        subject = 'New comment'
        message = f'New comment was added - {settings.SCHEMA}://{settings.DOMAIN}:{settings.PORT}{get_url}'
        from_email = 'no_reply@somecompany.com'
        to_email = [mail_to]
        celery_send_mail.delay(subject, message, from_email, to_email)

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comments


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'published')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ('username', 'text')


class ContactUsForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comments
from .forms import PostForm, CommentForm, ContactUsForm
from django.utils import timezone
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator
from django.contrib import messages
from .tasks import send_mail as celery_send_mail
from django.template.loader import render_to_string
from django.http import JsonResponse


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.published_date = timezone.now()
            post.save()
            subject = 'New post'
            message = 'New post was added'
            from_email = 'no_reply@somecompany.com'
            to_email = ['admin@somecompany.com']
            celery_send_mail.delay(subject, message, from_email, to_email)
            messages.add_message(request, messages.SUCCESS, 'Post added')
            return redirect('blog:posts_all')
    else:
        form = PostForm()
    return render(request, 'blog/post_new.html', {'form': form})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_l = post.comments_set.filter(published=True).all()
    paginator = Paginator(comment_l, 2)
    page = request.GET.get('page')
    comment_p = paginator.get_page(page)
    return render(request, 'blog/post_detail.html', {'post': post, 'comment': comment_p})


# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'post_detail.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(PostDetailView, self).get_context_data(**kwargs)
#         post = self.get_object()
#         comment = post.comments_set.filter(published=True).all()
#         paginator = Paginator(comment, 2)
#         context['comments'] = paginator.get_page(comment)
#         return context

    # def get_context_data(self):
    #     context = super(PostDetailView, self).get_context_data()
    #     _list = Comment.objects.filter(post=self.kwargs.get('pk'))
    #     paginator = Paginator(_list, 25) # Show 25 contacts per page
    #     page = request.GET.get('page')
    #     context['comments'] = paginator.get_page(page)
    #     return context


# @method_decorator(cache_page(10), 'dispatch')
class PostsListView(ListView):
    model = Post
    fields = ['title', 'text']
    queryset = Post.objects.filter(published=True)
    paginate_by = 10
    template_name = 'blog/posts_all.html'

    def get_object(self, **kwargs):
        user = self.request.user
        return user


class LoginUserPostsAllView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 10
    template_name = 'blog/user_posts.html'

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)

    def get_object(self, **kwargs):
        user = self.request.user
        return user


class UserPostDetailView(DetailView):
    model = Post
    template_name = 'blog/user_post_detail.html'

    def get_context_data(self, **kwargs):
        context = super(UserPostDetailView, self).get_context_data(**kwargs)
        post = self.get_object()
        context['comment'] = post.comments_set.filter(published=True).all()
        return context


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'text', 'published']
    template_name = 'blog/post_update.html'
    success_url = reverse_lazy('blog:user_posts')

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/delete_post.html'
    success_url = reverse_lazy('blog:user_posts')
    login_url = reverse_lazy('registration:login')


class CommentAddView(CreateView):
    model = Comments
    form_class = CommentForm
    template_name = 'blog/comment_add.html'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        subject = 'New comment'
        message = 'New comment was added'
        from_email = 'no_reply@somecompany.com'
        to_email = ['admin@somecompany.com']
        celery_send_mail.delay(subject, message, from_email, to_email)
        messages.add_message(self.request, messages.SUCCESS, 'Comment will be added after moderation')
        return super().form_valid(form)

    success_url = reverse_lazy('blog:posts_all')


def contact_us_view(request):
    data = dict()
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']
            to_email = ['admin@somecompany.com']
            celery_send_mail.delay(subject, message, from_email, to_email)
            # messages.add_message(request, messages.SUCCESS, 'Your message was sent successful')
            data['form_is_valid'] = True
            data['html_contact_us_success'] = render_to_string('blog/contact_us_success.html')
        else:
            data['form_is_valid'] = False
    else:
        form = ContactUsForm()
    context = {'form': form}
    data['html_form'] = render_to_string('blog/contact_us.html', context, request=request)
    return JsonResponse(data)


# def contact_us_view(request):
#     if request.method == "POST":
#         form = ContactUsForm(request.POST)
#         if form.is_valid():
#             subject = form.cleaned_data['subject']
#             message = form.cleaned_data['message']
#             from_email = form.cleaned_data['from_email']
#             to_email = ['admin@somecompany.com']
#             celery_send_mail.delay(subject, message, from_email, to_email)
#             messages.add_message(request, messages.SUCCESS, 'Message sent')
#             return redirect('blog:posts_all')
#     else:
#         form = ContactUsForm()
#     return render(request, "contact_us.html", context={"form": form})

templates/blog/comment_add.html
{% extends "base.html" %}
{% block content %}
    <h2>Add comment to post {{ post.title }} </h2>

    <form method="POST" class="post-form">
        {% csrf_token %}
    <table class="table table-hover">
        {{ form.as_table }}
    </table>
        <input type="submit" value="Save">
    </form>


{% endblock %}

templates/blog/contact_us.html
<form action="{% url 'blog:contact_us' %}" method="POST" class="js-contact-us-form">
{% csrf_token %}
<div class="modal-header">
    <h2 class="modal-title">Contact us</h2>
</div>
<div class="modal-body">
    {% load widget_tweaks %}
    <table class="table table-hover">
        {% for field in form %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% if form.is_bound %}
              {% if field.errors %}
                {% render_field field class+="form-control is-invalid" %}
                {% for error in field.errors %}
                  <div class="invalid-feedback">
                    {{ error }}
                  </div>
                {% endfor %}
              {% else %}
                {% render_field field class+="form-control is-valid" %}
              {% endif %}
            {% else %}
              {% render_field field class+="form-control" %}
            {% endif %}
          </div>
        {% endfor %}
    </table>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Sent</button>
</div>
</form>

templates/blog/contact_us_success.html
<div class="modal-header">
    <h4 class="modal-title">Success!</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Your message was sent, we will give you feedback ASAP</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>

templates/blog/delete_post.html
{% extends "base.html" %}
{% block content %}

<h1>Post delete</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <table class="table table-hover">
        {{ form.as_table }}
    </table>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

templates/blog/index.html
{% extends "base.html" %}
{% block content %}
    <h2>Index</h2>

<h1>All allowed links:</h1>

    <li><a href='{% url "user_management:registration" %}'>Registration</a></li>
    <li><a href='{% url "user_management:login" %}'>Login</a></li>
    <li><a href='{% url "user_management:logout" %}'>Logout</a></li>
    <li><a href='{% url "blog:add_post" %}'>Add post</a></li>
    <li><a href='{% url "blog:posts_all" %}'>List of all posts</a></li>

{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}
{% block content %}
    <h2>Post detail</h2>
    {{ object.instance.pk }}
    <div class="table-responsive">
        <table class="table align-middle">
            <tr>
                <td>Post</td>
                <td>{{ post.title }}</td>
            </tr>
            <tr>
                <td>Author</td>
                <td>{{ post.user }}</td>
            </tr>
            <tr>
                <td>Publication date</td>
                <td>{{ post.created_date }}</td>
            </tr>
            <tr>
                <td>Text</td>
                <td>{{ post.text }}</td>
            </tr>
        </table>
    </div>
    <h2>Comments</h2>
    <ul class="list-group list-group-flush">
    {% for a in comment %}
        <li class="list-group-item"><strong>{{ a.username }}</strong><br>
            {{ a.text }}</li>
    {% endfor %}
    </ul>

<div class="pagination">
    <span class="step-links">
        {% if comment.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ comment.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ comment.number }} of {{ comment.paginator.num_pages }}.
        </span>

        {% if comment.has_next %}
            <a href="?page={{ comment.next_page_number }}">next</a>
            <a href="?page={{ comment.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
        <p><a href='{% url "blog:comment_add" pk=post.id %}'>Add comment</a></p>

{% endblock %}

templates/blog/post_new.html
{% extends "base.html" %}
{% block content %}
    <h2>New post</h2>
    <form action= "{% url 'blog:add_post' %}" method="POST" class="post-form">
        {% csrf_token %}
        <table class="table align-middle">
            {{ form.as_table }}
        </table>
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

templates/blog/post_update.html
{% extends "base.html" %}
{% block content %}
    <h2>Post update</h2>
    <form action= "{% url 'blog:post_update' form.instance.pk %}" method="POST" class="post-form">
        {% csrf_token %}
    <table class="table table-hover">
        {{ form.as_table }}
    </table>
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

templates/blog/posts_all.html
{% extends "base.html" %}
{% block content %}
    <h2>All posts</h2>

    <table class="table table-hover">
        <thead class="table-dark">
        <tr>
            <td>Author</td>
            <td>Title</td>
            <td>Publication date</td>
        </tr>
        </thead>
        <tbody>
        {% for a in post_list %}
        <tr>
            <td><a href="{% url 'user_management:user_detail_pub' pk=a.user.id %}">{{ a.user }}</a></td>
            <td><a href='{% url "blog:post_detail" pk=a.id %}'>{{ a.title }}</a></td>
            <td>{{ a.created_date }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/blog/user_post_detail.html
{% extends "base.html" %}
{% block content %}
    <h2>Post detail</h2>
    {{ object.instance.pk }}
    <table class="table table-hover">
        <tr>
            <td>Post</td>
            <td>{{ post.title }}</td>
        </tr>
        <tr>
            <td>Created date</td>
            <td>{{ object.created_date }}</td>
        </tr>
        <tr>
            <td>Text</td>
            <td>{{ object.text }}</td>
        </tr>
    </table>

    <h2>Comments</h2>
    <ul class="list-group list-group-flush">
        {% for a in comment %}
    <li class="list-group-item"><strong>{{ a.username }}</strong><br>
        {{ a.text }}</li>
    {% endfor %}
    </ul>
    <p><a href='{% url "blog:post_update" pk=object.id %}'>Update</a><br>
    <a href='{% url "blog:post_delete" pk=object.id %}'>Delete post</a>

{% endblock %}

templates/blog/user_posts.html
{% extends "base.html" %}
{% block content %}
    <h2>All posts</h2>
    <div class="table-responsive">
        <table class="table align-middle">
            <thead class="table-dark">
            <tr>
                <td>Post</td>
                <td>Created at</td>
                <td>Text</td>
                <td>Published?</td>
            </tr>
            </thead>
            <tbody>
                {% for a in post_list %}
            <tr>
                <td><a href='{% url "blog:user_post_detail" pk=a.id %}'>{{ a.title }}</a></td>
                <td>{{ a.created_date }}</td>
                <td>{{ a.text }}</td>
                <td>{% if a.published %}
                Yes
                {% else %}
                No
                {% endif %}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}