blog/urls.py
from django.urls import path
from django.shortcuts import render
from . import views

app_name = 'blog'
urlpatterns = [
    # path('', views.index_view, name='index'),
    path('post-add/', views.post_new, name='add_post'),
    # path('post-detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post-detail/<int:pk>/', views.post_detail, name='post_detail'),
    path('', views.PostsListView.as_view(), name='posts_all'),
    path('user-posts/', views.LoginUserPostsAllView.as_view(), name='user_posts'),
    path('post/<int:pk>/comments', views.CommentAddView.as_view(), name='comment_add'),
    path('post-update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('contact-us/', views.contact_us_view, name='contact_us'),
    path('user_post-detail/<int:pk>/', views.UserPostDetailView.as_view(), name='user_post_detail'),
    path('post-delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user_management.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

user_management/urls.py
from django.urls import include, path
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from . import views


app_name = 'user_management'
urlpatterns = [
    path('registration/', views.RegistrationView.as_view(), name='registration'),

    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("user-detail/", views.UserDetailView.as_view(), name="user_detail"),
    path("user-update/", views.UserUpdateView.as_view(), name="user_update"),
    path("user-detail-pub/<int:pk>/", views.UserProfilePublicDetailView.as_view(), name="user_detail_pub")
]

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Local Library{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
      integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
      crossorigin="anonymous"></script>
  <script src="{% static 'js/blog.js' %}"></script>
  {% block extra_css %}
  {% endblock %}
  {% block extra_js %}
  {% endblock %}

    <!-- Add additional CSS in static file -->

</head>
<body>
<div class="container" style="padding-top: 60px;">
{% if messages %}
<div class="row">
  <div class="col-sm-12">
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  </div>
</div>
{% endif %}
</div>


<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'user_management:user_detail' %}">{{ request.user.get_username }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% else %}
    <a class="navbar-brand" href="{% url 'user_management:login' %}?next={{ request.path }}">Login</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'user_management:registration' %}?next={{ request.path }}">Registration</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    {% endif %}
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <div class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:posts_all' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-contact-us" data-url="{% url 'blog:contact_us' %}">Contact us</a>
        </li>
        {% if request.user.is_authenticated %}
        <div class="nav-item dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            User functions
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'user_management:user_detail' %}">My profile</a></li>
            <li><a class="dropdown-item" href="{% url 'blog:user_posts' %}">My posts</a></li>
            <li><a class="dropdown-item" href="{% url 'blog:add_post' %}">Add new post</a></li>
            <li><a class="dropdown-item" href="{% url 'user_management:logout' %}?next={% url 'blog:posts_all' %}">Logout</a></li>
        {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>
<div class="container">
{% block content %}{% endblock %}

<div class="modal fade" id="modal-contact-us">
  <div class="modal-dialog">
    <div class="modal-content">

    </div>
  </div>
</div>

    {% block pagination %}
    {% if is_paginated %}
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
          {% endif %}
        </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        </li>
          {% endif %}
      </ul>
    </nav>
    {% endif %}
    {% endblock %}



</div>
</div>
</div>
</body>
</html>